name: MAJOR 48h Gate
on:
  pull_request:
  workflow_dispatch:

jobs:
  hold:
    if: contains(toJson(github.event.pull_request.labels), 'MAJOR')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const opened = new Date(context.payload.pull_request.created_at).getTime();
            const hours = (Date.now() - opened) / 36e5;
            if (hours < 48) core.setFailed(`MAJOR requires >=48h; current=${hours.toFixed(1)}h`);
