name: MAJOR Hold (6-min demo)
on: { pull_request: { types: [opened, labeled, synchronize, reopened] } }
jobs:
  hold:
    if: contains(join(fromJson('["' + join(github.event.pull_request.labels.*.name, '","') + '"]'), ','), 'MAJOR_TEST')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const opened = new Date(pr.created_at).getTime();
            const minutes = (Date.now() - opened) / 60000;
            if (minutes < 6) core.setFailed(`Needs >=6 minutes (demo); current=${minutes.toFixed(1)}m`);
