name: CI Validate
on:
  pull_request:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -q pyyaml
      - name: Validate headers and DAM tags
        run: python scripts/validate_claims.py
